language: perl
sudo: false
branches:
  except:
    - /issue\d+/
perl:
  - 5.8.1
  - 5.8.3
  - 5.8.6
  - 5.8.7
  - 5.8.8
  - 5.8.9
  - 5.10.1
  - 5.12.3
  - 5.14.4
  - 5.16.3
  - 5.18.4
  - 5.20.3
  - 5.22.3
  - 5.24.2
  - 5.26.1
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR
install:
  - export AUTOMATED_TESTING=1 HARNESS_TIMER=1 AUTHOR_TESTING=0 RELEASE_TESTING=0
  - cpanm --quiet --installdeps --notest .
  - cpanm --quiet --installdeps --with-develop --notest . || /bin/true
